/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventTypeEntity model module.
 * @module model/EventTypeEntity
 * @version 0.0.1
 */
class EventTypeEntity {
    /**
     * Constructs a new <code>EventTypeEntity</code>.
     * EventTypeEntity model
     * @alias module:model/EventTypeEntity
     */
    constructor() { 
        
        EventTypeEntity.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EventTypeEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventTypeEntity} obj Optional instance to populate.
     * @return {module:model/EventTypeEntity} The populated <code>EventTypeEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventTypeEntity();

            if (data.hasOwnProperty('event_type_id')) {
                obj['event_type_id'] = ApiClient.convertToType(data['event_type_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventTypeEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventTypeEntity</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['color'] && !(typeof data['color'] === 'string' || data['color'] instanceof String)) {
            throw new Error("Expected the field `color` to be a primitive type in the JSON string but got " + data['color']);
        }

        return true;
    }


}



/**
 * ID of the event type record
 * @member {Number} event_type_id
 */
EventTypeEntity.prototype['event_type_id'] = undefined;

/**
 * Name of the event type (Campout, Meeting, etc)
 * @member {String} name
 */
EventTypeEntity.prototype['name'] = undefined;

/**
 * Color used to display events of this type on the TroopTrack calendar
 * @member {String} color
 */
EventTypeEntity.prototype['color'] = undefined;






export default EventTypeEntity;

