/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV1YouthsYouth from './PostV1YouthsYouth';

/**
 * The PostV1Youths model module.
 * @module model/PostV1Youths
 * @version 0.0.1
 */
class PostV1Youths {
    /**
     * Constructs a new <code>PostV1Youths</code>.
     * Create a youth
     * @alias module:model/PostV1Youths
     */
    constructor() { 
        
        PostV1Youths.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV1Youths</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1Youths} obj Optional instance to populate.
     * @return {module:model/PostV1Youths} The populated <code>PostV1Youths</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1Youths();

            if (data.hasOwnProperty('youth')) {
                obj['youth'] = PostV1YouthsYouth.constructFromObject(data['youth']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1Youths</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1Youths</code>.
     */
    static validateJSON(data) {
        // validate the optional field `youth`
        if (data['youth']) { // data not null
          PostV1YouthsYouth.validateJSON(data['youth']);
        }

        return true;
    }


}



/**
 * @member {module:model/PostV1YouthsYouth} youth
 */
PostV1Youths.prototype['youth'] = undefined;






export default PostV1Youths;

