/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1MailingListsIdMessage model module.
 * @module model/PostV1MailingListsIdMessage
 * @version 0.0.1
 */
class PostV1MailingListsIdMessage {
    /**
     * Constructs a new <code>PostV1MailingListsIdMessage</code>.
     * @alias module:model/PostV1MailingListsIdMessage
     * @param subject {String} 
     * @param body {String} 
     */
    constructor(subject, body) { 
        
        PostV1MailingListsIdMessage.initialize(this, subject, body);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, subject, body) { 
        obj['subject'] = subject;
        obj['body'] = body;
    }

    /**
     * Constructs a <code>PostV1MailingListsIdMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1MailingListsIdMessage} obj Optional instance to populate.
     * @return {module:model/PostV1MailingListsIdMessage} The populated <code>PostV1MailingListsIdMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1MailingListsIdMessage();

            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1MailingListsIdMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1MailingListsIdMessage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV1MailingListsIdMessage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['subject'] && !(typeof data['subject'] === 'string' || data['subject'] instanceof String)) {
            throw new Error("Expected the field `subject` to be a primitive type in the JSON string but got " + data['subject']);
        }
        // ensure the json data is a string
        if (data['body'] && !(typeof data['body'] === 'string' || data['body'] instanceof String)) {
            throw new Error("Expected the field `body` to be a primitive type in the JSON string but got " + data['body']);
        }

        return true;
    }


}

PostV1MailingListsIdMessage.RequiredProperties = ["subject", "body"];

/**
 * @member {String} subject
 */
PostV1MailingListsIdMessage.prototype['subject'] = undefined;

/**
 * @member {String} body
 */
PostV1MailingListsIdMessage.prototype['body'] = undefined;






export default PostV1MailingListsIdMessage;

