/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1UsersIdUser model module.
 * @module model/PostV1UsersIdUser
 * @version 0.0.1
 */
class PostV1UsersIdUser {
    /**
     * Constructs a new <code>PostV1UsersIdUser</code>.
     * @alias module:model/PostV1UsersIdUser
     */
    constructor() { 
        
        PostV1UsersIdUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV1UsersIdUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1UsersIdUser} obj Optional instance to populate.
     * @return {module:model/PostV1UsersIdUser} The populated <code>PostV1UsersIdUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1UsersIdUser();

            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('born_on')) {
                obj['born_on'] = ApiClient.convertToType(data['born_on'], 'String');
            }
            if (data.hasOwnProperty('home_phone')) {
                obj['home_phone'] = ApiClient.convertToType(data['home_phone'], 'String');
            }
            if (data.hasOwnProperty('cell_phone')) {
                obj['cell_phone'] = ApiClient.convertToType(data['cell_phone'], 'String');
            }
            if (data.hasOwnProperty('profile_photo_file_name')) {
                obj['profile_photo_file_name'] = ApiClient.convertToType(data['profile_photo_file_name'], 'String');
            }
            if (data.hasOwnProperty('profile_photo_file_content')) {
                obj['profile_photo_file_content'] = ApiClient.convertToType(data['profile_photo_file_content'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1UsersIdUser</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1UsersIdUser</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['born_on'] && !(typeof data['born_on'] === 'string' || data['born_on'] instanceof String)) {
            throw new Error("Expected the field `born_on` to be a primitive type in the JSON string but got " + data['born_on']);
        }
        // ensure the json data is a string
        if (data['home_phone'] && !(typeof data['home_phone'] === 'string' || data['home_phone'] instanceof String)) {
            throw new Error("Expected the field `home_phone` to be a primitive type in the JSON string but got " + data['home_phone']);
        }
        // ensure the json data is a string
        if (data['cell_phone'] && !(typeof data['cell_phone'] === 'string' || data['cell_phone'] instanceof String)) {
            throw new Error("Expected the field `cell_phone` to be a primitive type in the JSON string but got " + data['cell_phone']);
        }
        // ensure the json data is a string
        if (data['profile_photo_file_name'] && !(typeof data['profile_photo_file_name'] === 'string' || data['profile_photo_file_name'] instanceof String)) {
            throw new Error("Expected the field `profile_photo_file_name` to be a primitive type in the JSON string but got " + data['profile_photo_file_name']);
        }
        // ensure the json data is a string
        if (data['profile_photo_file_content'] && !(typeof data['profile_photo_file_content'] === 'string' || data['profile_photo_file_content'] instanceof String)) {
            throw new Error("Expected the field `profile_photo_file_content` to be a primitive type in the JSON string but got " + data['profile_photo_file_content']);
        }

        return true;
    }


}



/**
 * @member {String} last_name
 */
PostV1UsersIdUser.prototype['last_name'] = undefined;

/**
 * @member {String} first_name
 */
PostV1UsersIdUser.prototype['first_name'] = undefined;

/**
 * @member {String} email
 */
PostV1UsersIdUser.prototype['email'] = undefined;

/**
 * @member {String} born_on
 */
PostV1UsersIdUser.prototype['born_on'] = undefined;

/**
 * @member {String} home_phone
 */
PostV1UsersIdUser.prototype['home_phone'] = undefined;

/**
 * @member {String} cell_phone
 */
PostV1UsersIdUser.prototype['cell_phone'] = undefined;

/**
 * @member {String} profile_photo_file_name
 */
PostV1UsersIdUser.prototype['profile_photo_file_name'] = undefined;

/**
 * @member {String} profile_photo_file_content
 */
PostV1UsersIdUser.prototype['profile_photo_file_content'] = undefined;






export default PostV1UsersIdUser;

