/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1PhotoAlbumsId model module.
 * @module model/PostV1PhotoAlbumsId
 * @version 0.0.1
 */
class PostV1PhotoAlbumsId {
    /**
     * Constructs a new <code>PostV1PhotoAlbumsId</code>.
     * Upload a new photo to a photo album
     * @alias module:model/PostV1PhotoAlbumsId
     * @param photoFileExtension {String} 
     * @param photoFileContent {String} 
     */
    constructor(photoFileExtension, photoFileContent) { 
        
        PostV1PhotoAlbumsId.initialize(this, photoFileExtension, photoFileContent);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, photoFileExtension, photoFileContent) { 
        obj['photo_file_extension'] = photoFileExtension;
        obj['photo_file_content'] = photoFileContent;
    }

    /**
     * Constructs a <code>PostV1PhotoAlbumsId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1PhotoAlbumsId} obj Optional instance to populate.
     * @return {module:model/PostV1PhotoAlbumsId} The populated <code>PostV1PhotoAlbumsId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1PhotoAlbumsId();

            if (data.hasOwnProperty('photo_file_extension')) {
                obj['photo_file_extension'] = ApiClient.convertToType(data['photo_file_extension'], 'String');
            }
            if (data.hasOwnProperty('photo_file_content')) {
                obj['photo_file_content'] = ApiClient.convertToType(data['photo_file_content'], 'String');
            }
            if (data.hasOwnProperty('album_name')) {
                obj['album_name'] = ApiClient.convertToType(data['album_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1PhotoAlbumsId</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1PhotoAlbumsId</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV1PhotoAlbumsId.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['photo_file_extension'] && !(typeof data['photo_file_extension'] === 'string' || data['photo_file_extension'] instanceof String)) {
            throw new Error("Expected the field `photo_file_extension` to be a primitive type in the JSON string but got " + data['photo_file_extension']);
        }
        // ensure the json data is a string
        if (data['photo_file_content'] && !(typeof data['photo_file_content'] === 'string' || data['photo_file_content'] instanceof String)) {
            throw new Error("Expected the field `photo_file_content` to be a primitive type in the JSON string but got " + data['photo_file_content']);
        }
        // ensure the json data is a string
        if (data['album_name'] && !(typeof data['album_name'] === 'string' || data['album_name'] instanceof String)) {
            throw new Error("Expected the field `album_name` to be a primitive type in the JSON string but got " + data['album_name']);
        }

        return true;
    }


}

PostV1PhotoAlbumsId.RequiredProperties = ["photo_file_extension", "photo_file_content"];

/**
 * @member {String} photo_file_extension
 */
PostV1PhotoAlbumsId.prototype['photo_file_extension'] = undefined;

/**
 * @member {String} photo_file_content
 */
PostV1PhotoAlbumsId.prototype['photo_file_content'] = undefined;

/**
 * @member {String} album_name
 */
PostV1PhotoAlbumsId.prototype['album_name'] = undefined;






export default PostV1PhotoAlbumsId;

