/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1UserAchievementsIdAchievementChildrenInner model module.
 * @module model/PostV1UserAchievementsIdAchievementChildrenInner
 * @version 0.0.1
 */
class PostV1UserAchievementsIdAchievementChildrenInner {
    /**
     * Constructs a new <code>PostV1UserAchievementsIdAchievementChildrenInner</code>.
     * @alias module:model/PostV1UserAchievementsIdAchievementChildrenInner
     * @param id {Number} Id of the requirement to be updated
     * @param completedOn {String} Date the requirement was completed in YYYY-MM-DD format
     */
    constructor(id, completedOn) { 
        
        PostV1UserAchievementsIdAchievementChildrenInner.initialize(this, id, completedOn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, completedOn) { 
        obj['id'] = id;
        obj['completed_on'] = completedOn;
    }

    /**
     * Constructs a <code>PostV1UserAchievementsIdAchievementChildrenInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1UserAchievementsIdAchievementChildrenInner} obj Optional instance to populate.
     * @return {module:model/PostV1UserAchievementsIdAchievementChildrenInner} The populated <code>PostV1UserAchievementsIdAchievementChildrenInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1UserAchievementsIdAchievementChildrenInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('completed_on')) {
                obj['completed_on'] = ApiClient.convertToType(data['completed_on'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1UserAchievementsIdAchievementChildrenInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1UserAchievementsIdAchievementChildrenInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV1UserAchievementsIdAchievementChildrenInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['completed_on'] && !(typeof data['completed_on'] === 'string' || data['completed_on'] instanceof String)) {
            throw new Error("Expected the field `completed_on` to be a primitive type in the JSON string but got " + data['completed_on']);
        }

        return true;
    }


}

PostV1UserAchievementsIdAchievementChildrenInner.RequiredProperties = ["id", "completed_on"];

/**
 * Id of the requirement to be updated
 * @member {Number} id
 */
PostV1UserAchievementsIdAchievementChildrenInner.prototype['id'] = undefined;

/**
 * Date the requirement was completed in YYYY-MM-DD format
 * @member {String} completed_on
 */
PostV1UserAchievementsIdAchievementChildrenInner.prototype['completed_on'] = undefined;






export default PostV1UserAchievementsIdAchievementChildrenInner;

