/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1YouthsYouth model module.
 * @module model/PostV1YouthsYouth
 * @version 0.0.1
 */
class PostV1YouthsYouth {
    /**
     * Constructs a new <code>PostV1YouthsYouth</code>.
     * @alias module:model/PostV1YouthsYouth
     * @param lastName {String} 
     * @param firstName {String} 
     */
    constructor(lastName, firstName) { 
        
        PostV1YouthsYouth.initialize(this, lastName, firstName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, lastName, firstName) { 
        obj['last_name'] = lastName;
        obj['first_name'] = firstName;
    }

    /**
     * Constructs a <code>PostV1YouthsYouth</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1YouthsYouth} obj Optional instance to populate.
     * @return {module:model/PostV1YouthsYouth} The populated <code>PostV1YouthsYouth</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1YouthsYouth();

            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('born_on')) {
                obj['born_on'] = ApiClient.convertToType(data['born_on'], 'String');
            }
            if (data.hasOwnProperty('scout')) {
                obj['scout'] = ApiClient.convertToType(data['scout'], 'String');
            }
            if (data.hasOwnProperty('home_phone')) {
                obj['home_phone'] = ApiClient.convertToType(data['home_phone'], 'String');
            }
            if (data.hasOwnProperty('cell_phone')) {
                obj['cell_phone'] = ApiClient.convertToType(data['cell_phone'], 'String');
            }
            if (data.hasOwnProperty('patrol_id')) {
                obj['patrol_id'] = ApiClient.convertToType(data['patrol_id'], 'Number');
            }
            if (data.hasOwnProperty('household_id')) {
                obj['household_id'] = ApiClient.convertToType(data['household_id'], 'Number');
            }
            if (data.hasOwnProperty('profile_photo')) {
                obj['profile_photo'] = ApiClient.convertToType(data['profile_photo'], 'String');
            }
            if (data.hasOwnProperty('leadership_position_id')) {
                obj['leadership_position_id'] = ApiClient.convertToType(data['leadership_position_id'], 'Number');
            }
            if (data.hasOwnProperty('create_money_account')) {
                obj['create_money_account'] = ApiClient.convertToType(data['create_money_account'], 'Boolean');
            }
            if (data.hasOwnProperty('send_invite')) {
                obj['send_invite'] = ApiClient.convertToType(data['send_invite'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1YouthsYouth</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1YouthsYouth</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV1YouthsYouth.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['born_on'] && !(typeof data['born_on'] === 'string' || data['born_on'] instanceof String)) {
            throw new Error("Expected the field `born_on` to be a primitive type in the JSON string but got " + data['born_on']);
        }
        // ensure the json data is a string
        if (data['scout'] && !(typeof data['scout'] === 'string' || data['scout'] instanceof String)) {
            throw new Error("Expected the field `scout` to be a primitive type in the JSON string but got " + data['scout']);
        }
        // ensure the json data is a string
        if (data['home_phone'] && !(typeof data['home_phone'] === 'string' || data['home_phone'] instanceof String)) {
            throw new Error("Expected the field `home_phone` to be a primitive type in the JSON string but got " + data['home_phone']);
        }
        // ensure the json data is a string
        if (data['cell_phone'] && !(typeof data['cell_phone'] === 'string' || data['cell_phone'] instanceof String)) {
            throw new Error("Expected the field `cell_phone` to be a primitive type in the JSON string but got " + data['cell_phone']);
        }
        // ensure the json data is a string
        if (data['profile_photo'] && !(typeof data['profile_photo'] === 'string' || data['profile_photo'] instanceof String)) {
            throw new Error("Expected the field `profile_photo` to be a primitive type in the JSON string but got " + data['profile_photo']);
        }

        return true;
    }


}

PostV1YouthsYouth.RequiredProperties = ["last_name", "first_name"];

/**
 * @member {String} last_name
 */
PostV1YouthsYouth.prototype['last_name'] = undefined;

/**
 * @member {String} first_name
 */
PostV1YouthsYouth.prototype['first_name'] = undefined;

/**
 * @member {String} email
 */
PostV1YouthsYouth.prototype['email'] = undefined;

/**
 * @member {String} born_on
 */
PostV1YouthsYouth.prototype['born_on'] = undefined;

/**
 * @member {String} scout
 */
PostV1YouthsYouth.prototype['scout'] = undefined;

/**
 * @member {String} home_phone
 */
PostV1YouthsYouth.prototype['home_phone'] = undefined;

/**
 * @member {String} cell_phone
 */
PostV1YouthsYouth.prototype['cell_phone'] = undefined;

/**
 * @member {Number} patrol_id
 */
PostV1YouthsYouth.prototype['patrol_id'] = undefined;

/**
 * @member {Number} household_id
 */
PostV1YouthsYouth.prototype['household_id'] = undefined;

/**
 * @member {String} profile_photo
 */
PostV1YouthsYouth.prototype['profile_photo'] = undefined;

/**
 * @member {Number} leadership_position_id
 */
PostV1YouthsYouth.prototype['leadership_position_id'] = undefined;

/**
 * @member {Boolean} create_money_account
 */
PostV1YouthsYouth.prototype['create_money_account'] = undefined;

/**
 * @member {Boolean} send_invite
 */
PostV1YouthsYouth.prototype['send_invite'] = undefined;






export default PostV1YouthsYouth;

