/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV1UsersIdUser from './PostV1UsersIdUser';

/**
 * The PostV1UsersId model module.
 * @module model/PostV1UsersId
 * @version 0.0.1
 */
class PostV1UsersId {
    /**
     * Constructs a new <code>PostV1UsersId</code>.
     * Update detailed information about a user
     * @alias module:model/PostV1UsersId
     */
    constructor() { 
        
        PostV1UsersId.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV1UsersId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1UsersId} obj Optional instance to populate.
     * @return {module:model/PostV1UsersId} The populated <code>PostV1UsersId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1UsersId();

            if (data.hasOwnProperty('user')) {
                obj['user'] = PostV1UsersIdUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1UsersId</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1UsersId</code>.
     */
    static validateJSON(data) {
        // validate the optional field `user`
        if (data['user']) { // data not null
          PostV1UsersIdUser.validateJSON(data['user']);
        }

        return true;
    }


}



/**
 * @member {module:model/PostV1UsersIdUser} user
 */
PostV1UsersId.prototype['user'] = undefined;






export default PostV1UsersId;

