/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV1EventsEventIdAttendanceEventTrackersInner from './PostV1EventsEventIdAttendanceEventTrackersInner';

/**
 * The PostV1EventsEventIdAttendance model module.
 * @module model/PostV1EventsEventIdAttendance
 * @version 0.0.1
 */
class PostV1EventsEventIdAttendance {
    /**
     * Constructs a new <code>PostV1EventsEventIdAttendance</code>.
     * Record attendance at an event
     * @alias module:model/PostV1EventsEventIdAttendance
     * @param eventTrackers {Array.<module:model/PostV1EventsEventIdAttendanceEventTrackersInner>} 
     */
    constructor(eventTrackers) { 
        
        PostV1EventsEventIdAttendance.initialize(this, eventTrackers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, eventTrackers) { 
        obj['event_trackers'] = eventTrackers;
    }

    /**
     * Constructs a <code>PostV1EventsEventIdAttendance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1EventsEventIdAttendance} obj Optional instance to populate.
     * @return {module:model/PostV1EventsEventIdAttendance} The populated <code>PostV1EventsEventIdAttendance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1EventsEventIdAttendance();

            if (data.hasOwnProperty('event_trackers')) {
                obj['event_trackers'] = ApiClient.convertToType(data['event_trackers'], [PostV1EventsEventIdAttendanceEventTrackersInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1EventsEventIdAttendance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1EventsEventIdAttendance</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV1EventsEventIdAttendance.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['event_trackers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['event_trackers'])) {
                throw new Error("Expected the field `event_trackers` to be an array in the JSON data but got " + data['event_trackers']);
            }
            // validate the optional field `event_trackers` (array)
            for (const item of data['event_trackers']) {
                PostV1EventsEventIdAttendanceEventTrackersInner.validateJSON(item);
            };
        }

        return true;
    }


}

PostV1EventsEventIdAttendance.RequiredProperties = ["event_trackers"];

/**
 * @member {Array.<module:model/PostV1EventsEventIdAttendanceEventTrackersInner>} event_trackers
 */
PostV1EventsEventIdAttendance.prototype['event_trackers'] = undefined;






export default PostV1EventsEventIdAttendance;

