/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV1EventsEvent from './PostV1EventsEvent';

/**
 * The PostV1Events model module.
 * @module model/PostV1Events
 * @version 0.0.1
 */
class PostV1Events {
    /**
     * Constructs a new <code>PostV1Events</code>.
     * Create an event
     * @alias module:model/PostV1Events
     */
    constructor() { 
        
        PostV1Events.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV1Events</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1Events} obj Optional instance to populate.
     * @return {module:model/PostV1Events} The populated <code>PostV1Events</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1Events();

            if (data.hasOwnProperty('event')) {
                obj['event'] = PostV1EventsEvent.constructFromObject(data['event']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1Events</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1Events</code>.
     */
    static validateJSON(data) {
        // validate the optional field `event`
        if (data['event']) { // data not null
          PostV1EventsEvent.validateJSON(data['event']);
        }

        return true;
    }


}



/**
 * @member {module:model/PostV1EventsEvent} event
 */
PostV1Events.prototype['event'] = undefined;






export default PostV1Events;

