/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PutV1EventsIdRsvp model module.
 * @module model/PutV1EventsIdRsvp
 * @version 0.0.1
 */
class PutV1EventsIdRsvp {
    /**
     * Constructs a new <code>PutV1EventsIdRsvp</code>.
     * RSVP to an event
     * @alias module:model/PutV1EventsIdRsvp
     * @param userId {Number} ID of the user for whom you are RSVP'ing. Must be within your scope as a user AND must be invited to the event.
     * @param statusCd {String} yes: Coming. no: Not coming. tbd: No clue.
     */
    constructor(userId, statusCd) { 
        
        PutV1EventsIdRsvp.initialize(this, userId, statusCd);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, statusCd) { 
        obj['user_id'] = userId;
        obj['status_cd'] = statusCd;
    }

    /**
     * Constructs a <code>PutV1EventsIdRsvp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PutV1EventsIdRsvp} obj Optional instance to populate.
     * @return {module:model/PutV1EventsIdRsvp} The populated <code>PutV1EventsIdRsvp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutV1EventsIdRsvp();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('status_cd')) {
                obj['status_cd'] = ApiClient.convertToType(data['status_cd'], 'String');
            }
            if (data.hasOwnProperty('number_of_youth_guests')) {
                obj['number_of_youth_guests'] = ApiClient.convertToType(data['number_of_youth_guests'], 'Number');
            }
            if (data.hasOwnProperty('number_of_adult_guests')) {
                obj['number_of_adult_guests'] = ApiClient.convertToType(data['number_of_adult_guests'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PutV1EventsIdRsvp</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PutV1EventsIdRsvp</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PutV1EventsIdRsvp.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status_cd'] && !(typeof data['status_cd'] === 'string' || data['status_cd'] instanceof String)) {
            throw new Error("Expected the field `status_cd` to be a primitive type in the JSON string but got " + data['status_cd']);
        }

        return true;
    }


}

PutV1EventsIdRsvp.RequiredProperties = ["user_id", "status_cd"];

/**
 * ID of the user for whom you are RSVP'ing. Must be within your scope as a user AND must be invited to the event.
 * @member {Number} user_id
 */
PutV1EventsIdRsvp.prototype['user_id'] = undefined;

/**
 * yes: Coming. no: Not coming. tbd: No clue.
 * @member {String} status_cd
 */
PutV1EventsIdRsvp.prototype['status_cd'] = undefined;

/**
 * @member {Number} number_of_youth_guests
 */
PutV1EventsIdRsvp.prototype['number_of_youth_guests'] = undefined;

/**
 * @member {Number} number_of_adult_guests
 */
PutV1EventsIdRsvp.prototype['number_of_adult_guests'] = undefined;






export default PutV1EventsIdRsvp;

