/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AchievementEntity from '../model/AchievementEntity';

/**
* Achievements service.
* @module api/AchievementsApi
* @version 0.0.1
*/
export default class AchievementsApi {

    /**
    * Constructs a new AchievementsApi. 
    * @alias module:api/AchievementsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV1Achievements operation.
     * @callback module:api/AchievementsApi~getV1AchievementsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AchievementEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of available achievements for the member
     * @param {String} xPartnerToken Your secret partner token
     * @param {String} xUserToken The token you received when you authenticated the user
     * @param {module:api/AchievementsApi~getV1AchievementsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AchievementEntity}
     */
    getV1Achievements(xPartnerToken, xUserToken, callback) {
      let postBody = null;
      // verify the required parameter 'xPartnerToken' is set
      if (xPartnerToken === undefined || xPartnerToken === null) {
        throw new Error("Missing the required parameter 'xPartnerToken' when calling getV1Achievements");
      }
      // verify the required parameter 'xUserToken' is set
      if (xUserToken === undefined || xUserToken === null) {
        throw new Error("Missing the required parameter 'xUserToken' when calling getV1Achievements");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Partner-Token': xPartnerToken,
        'X-User-Token': xUserToken
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AchievementEntity;
      return this.apiClient.callApi(
        '/v1/achievements', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV1AchievementsId operation.
     * @callback module:api/AchievementsApi~getV1AchievementsIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AchievementEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns detailed information about an achievement
     * @param {String} xPartnerToken Your secret partner token
     * @param {String} xUserToken The token you received when you authenticated the user
     * @param {Number} id 
     * @param {Number} awardTypeId 
     * @param {module:api/AchievementsApi~getV1AchievementsIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AchievementEntity}
     */
    getV1AchievementsId(xPartnerToken, xUserToken, id, awardTypeId, callback) {
      let postBody = null;
      // verify the required parameter 'xPartnerToken' is set
      if (xPartnerToken === undefined || xPartnerToken === null) {
        throw new Error("Missing the required parameter 'xPartnerToken' when calling getV1AchievementsId");
      }
      // verify the required parameter 'xUserToken' is set
      if (xUserToken === undefined || xUserToken === null) {
        throw new Error("Missing the required parameter 'xUserToken' when calling getV1AchievementsId");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getV1AchievementsId");
      }
      // verify the required parameter 'awardTypeId' is set
      if (awardTypeId === undefined || awardTypeId === null) {
        throw new Error("Missing the required parameter 'awardTypeId' when calling getV1AchievementsId");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'award_type_id': awardTypeId
      };
      let headerParams = {
        'X-Partner-Token': xPartnerToken,
        'X-User-Token': xUserToken
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AchievementEntity;
      return this.apiClient.callApi(
        '/v1/achievements/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
