/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AwardTypeEntity from '../model/AwardTypeEntity';

/**
* AwardTypes service.
* @module api/AwardTypesApi
* @version 0.0.1
*/
export default class AwardTypesApi {

    /**
    * Constructs a new AwardTypesApi. 
    * @alias module:api/AwardTypesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV1AwardTypes operation.
     * @callback module:api/AwardTypesApi~getV1AwardTypesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AwardTypeEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of available award types for the member. Active achievements are not included.
     * @param {String} xPartnerToken Your secret partner token
     * @param {String} xUserToken The token you received when you authenticated the user
     * @param {module:api/AwardTypesApi~getV1AwardTypesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AwardTypeEntity}
     */
    getV1AwardTypes(xPartnerToken, xUserToken, callback) {
      let postBody = null;
      // verify the required parameter 'xPartnerToken' is set
      if (xPartnerToken === undefined || xPartnerToken === null) {
        throw new Error("Missing the required parameter 'xPartnerToken' when calling getV1AwardTypes");
      }
      // verify the required parameter 'xUserToken' is set
      if (xUserToken === undefined || xUserToken === null) {
        throw new Error("Missing the required parameter 'xUserToken' when calling getV1AwardTypes");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Partner-Token': xPartnerToken,
        'X-User-Token': xUserToken
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AwardTypeEntity;
      return this.apiClient.callApi(
        '/v1/award_types', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getV1AwardTypesId operation.
     * @callback module:api/AwardTypesApi~getV1AwardTypesIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AwardTypeEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns active achievements for a given award type.
     * @param {String} xPartnerToken Your secret partner token
     * @param {String} xUserToken The token you received when you authenticated the user
     * @param {Number} id 
     * @param {module:api/AwardTypesApi~getV1AwardTypesIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AwardTypeEntity}
     */
    getV1AwardTypesId(xPartnerToken, xUserToken, id, callback) {
      let postBody = null;
      // verify the required parameter 'xPartnerToken' is set
      if (xPartnerToken === undefined || xPartnerToken === null) {
        throw new Error("Missing the required parameter 'xPartnerToken' when calling getV1AwardTypesId");
      }
      // verify the required parameter 'xUserToken' is set
      if (xUserToken === undefined || xUserToken === null) {
        throw new Error("Missing the required parameter 'xUserToken' when calling getV1AwardTypesId");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getV1AwardTypesId");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Partner-Token': xPartnerToken,
        'X-User-Token': xUserToken
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AwardTypeEntity;
      return this.apiClient.callApi(
        '/v1/award_types/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
