/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MailingListEntity from '../model/MailingListEntity';
import PostV1MailingListsId from '../model/PostV1MailingListsId';

/**
* MailingLists service.
* @module api/MailingListsApi
* @version 0.0.1
*/
export default class MailingListsApi {

    /**
    * Constructs a new MailingListsApi. 
    * @alias module:api/MailingListsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV1MailingLists operation.
     * @callback module:api/MailingListsApi~getV1MailingListsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MailingListEntity>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of mailing lists relevant to the user
     * @param {String} xPartnerToken Your secret partner token
     * @param {String} xUserToken The token you received when you authenticated the user
     * @param {module:api/MailingListsApi~getV1MailingListsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MailingListEntity>}
     */
    getV1MailingLists(xPartnerToken, xUserToken, callback) {
      let postBody = null;
      // verify the required parameter 'xPartnerToken' is set
      if (xPartnerToken === undefined || xPartnerToken === null) {
        throw new Error("Missing the required parameter 'xPartnerToken' when calling getV1MailingLists");
      }
      // verify the required parameter 'xUserToken' is set
      if (xUserToken === undefined || xUserToken === null) {
        throw new Error("Missing the required parameter 'xUserToken' when calling getV1MailingLists");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Partner-Token': xPartnerToken,
        'X-User-Token': xUserToken
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [MailingListEntity];
      return this.apiClient.callApi(
        '/v1/mailing_lists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postV1MailingListsId operation.
     * @callback module:api/MailingListsApi~postV1MailingListsIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Post a message to a mailing list
     * @param {String} xPartnerToken Your secret partner token
     * @param {String} xUserToken The token you received when you authenticated the user
     * @param {String} id The ID of the list you want to post a message to
     * @param {module:model/PostV1MailingListsId} postV1MailingListsId 
     * @param {module:api/MailingListsApi~postV1MailingListsIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postV1MailingListsId(xPartnerToken, xUserToken, id, postV1MailingListsId, callback) {
      let postBody = postV1MailingListsId;
      // verify the required parameter 'xPartnerToken' is set
      if (xPartnerToken === undefined || xPartnerToken === null) {
        throw new Error("Missing the required parameter 'xPartnerToken' when calling postV1MailingListsId");
      }
      // verify the required parameter 'xUserToken' is set
      if (xUserToken === undefined || xUserToken === null) {
        throw new Error("Missing the required parameter 'xUserToken' when calling postV1MailingListsId");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling postV1MailingListsId");
      }
      // verify the required parameter 'postV1MailingListsId' is set
      if (postV1MailingListsId === undefined || postV1MailingListsId === null) {
        throw new Error("Missing the required parameter 'postV1MailingListsId' when calling postV1MailingListsId");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Partner-Token': xPartnerToken,
        'X-User-Token': xUserToken
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/mailing_lists/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
