/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* Offline service.
* @module api/OfflineApi
* @version 0.0.1
*/
export default class OfflineApi {

    /**
    * Constructs a new OfflineApi. 
    * @alias module:api/OfflineApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getV1Offline operation.
     * @callback module:api/OfflineApi~getV1OfflineCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all troop data for cacheing prior to going offline
     * @param {String} xPartnerToken Your secret partner token
     * @param {String} xUserToken The token you received when you authenticated the user
     * @param {String} troopId 
     * @param {module:api/OfflineApi~getV1OfflineCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getV1Offline(xPartnerToken, xUserToken, troopId, callback) {
      let postBody = null;
      // verify the required parameter 'xPartnerToken' is set
      if (xPartnerToken === undefined || xPartnerToken === null) {
        throw new Error("Missing the required parameter 'xPartnerToken' when calling getV1Offline");
      }
      // verify the required parameter 'xUserToken' is set
      if (xUserToken === undefined || xUserToken === null) {
        throw new Error("Missing the required parameter 'xUserToken' when calling getV1Offline");
      }
      // verify the required parameter 'troopId' is set
      if (troopId === undefined || troopId === null) {
        throw new Error("Missing the required parameter 'troopId' when calling getV1Offline");
      }

      let pathParams = {
      };
      let queryParams = {
        'troop_id': troopId
      };
      let headerParams = {
        'X-Partner-Token': xPartnerToken,
        'X-User-Token': xUserToken
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/offline', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
