/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.EventEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventEntity', function() {
    it('should create an instance of EventEntity', function() {
      // uncomment below and update the code to test EventEntity
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be.a(ApiTitle.EventEntity);
    });

    it('should have the property eventId (base name: "event_id")', function() {
      // uncomment below and update the code to test the property eventId
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property eventType (base name: "event_type")', function() {
      // uncomment below and update the code to test the property eventType
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property activityAt (base name: "activity_at")', function() {
      // uncomment below and update the code to test the property activityAt
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property endAt (base name: "end_at")', function() {
      // uncomment below and update the code to test the property endAt
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property textColor (base name: "text_color")', function() {
      // uncomment below and update the code to test the property textColor
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property isRegistrationClosed (base name: "is_registration_closed?")', function() {
      // uncomment below and update the code to test the property isRegistrationClosed
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

    it('should have the property paymentRequiredToRsvp (base name: "payment_required_to_rsvp")', function() {
      // uncomment below and update the code to test the property paymentRequiredToRsvp
      //var instance = new ApiTitle.EventEntity();
      //expect(instance).to.be();
    });

  });

}));
