/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.PhotoAlbumEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PhotoAlbumEntity', function() {
    it('should create an instance of PhotoAlbumEntity', function() {
      // uncomment below and update the code to test PhotoAlbumEntity
      //var instance = new ApiTitle.PhotoAlbumEntity();
      //expect(instance).to.be.a(ApiTitle.PhotoAlbumEntity);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ApiTitle.PhotoAlbumEntity();
      //expect(instance).to.be();
    });

    it('should have the property photoAlbumId (base name: "photo_album_id")', function() {
      // uncomment below and update the code to test the property photoAlbumId
      //var instance = new ApiTitle.PhotoAlbumEntity();
      //expect(instance).to.be();
    });

    it('should have the property photoCount (base name: "photo_count")', function() {
      // uncomment below and update the code to test the property photoCount
      //var instance = new ApiTitle.PhotoAlbumEntity();
      //expect(instance).to.be();
    });

    it('should have the property takenOn (base name: "taken_on")', function() {
      // uncomment below and update the code to test the property takenOn
      //var instance = new ApiTitle.PhotoAlbumEntity();
      //expect(instance).to.be();
    });

    it('should have the property troopPhotos (base name: "troop_photos")', function() {
      // uncomment below and update the code to test the property troopPhotos
      //var instance = new ApiTitle.PhotoAlbumEntity();
      //expect(instance).to.be();
    });

  });

}));
