/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.PostV1UserAchievementsIdAchievement();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostV1UserAchievementsIdAchievement', function() {
    it('should create an instance of PostV1UserAchievementsIdAchievement', function() {
      // uncomment below and update the code to test PostV1UserAchievementsIdAchievement
      //var instance = new ApiTitle.PostV1UserAchievementsIdAchievement();
      //expect(instance).to.be.a(ApiTitle.PostV1UserAchievementsIdAchievement);
    });

    it('should have the property completedOn (base name: "completed_on")', function() {
      // uncomment below and update the code to test the property completedOn
      //var instance = new ApiTitle.PostV1UserAchievementsIdAchievement();
      //expect(instance).to.be();
    });

    it('should have the property awardCardFrontImageContent (base name: "award_card_front_image_content")', function() {
      // uncomment below and update the code to test the property awardCardFrontImageContent
      //var instance = new ApiTitle.PostV1UserAchievementsIdAchievement();
      //expect(instance).to.be();
    });

    it('should have the property awardCardImagesType (base name: "award_card_images_type")', function() {
      // uncomment below and update the code to test the property awardCardImagesType
      //var instance = new ApiTitle.PostV1UserAchievementsIdAchievement();
      //expect(instance).to.be();
    });

    it('should have the property awardCardBackImageContent (base name: "award_card_back_image_content")', function() {
      // uncomment below and update the code to test the property awardCardBackImageContent
      //var instance = new ApiTitle.PostV1UserAchievementsIdAchievement();
      //expect(instance).to.be();
    });

    it('should have the property children (base name: "children")', function() {
      // uncomment below and update the code to test the property children
      //var instance = new ApiTitle.PostV1UserAchievementsIdAchievement();
      //expect(instance).to.be();
    });

  });

}));
