/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.PostV1YouthsYouth();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostV1YouthsYouth', function() {
    it('should create an instance of PostV1YouthsYouth', function() {
      // uncomment below and update the code to test PostV1YouthsYouth
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be.a(ApiTitle.PostV1YouthsYouth);
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property bornOn (base name: "born_on")', function() {
      // uncomment below and update the code to test the property bornOn
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property scout (base name: "scout")', function() {
      // uncomment below and update the code to test the property scout
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property homePhone (base name: "home_phone")', function() {
      // uncomment below and update the code to test the property homePhone
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property cellPhone (base name: "cell_phone")', function() {
      // uncomment below and update the code to test the property cellPhone
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property patrolId (base name: "patrol_id")', function() {
      // uncomment below and update the code to test the property patrolId
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property householdId (base name: "household_id")', function() {
      // uncomment below and update the code to test the property householdId
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property profilePhoto (base name: "profile_photo")', function() {
      // uncomment below and update the code to test the property profilePhoto
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property leadershipPositionId (base name: "leadership_position_id")', function() {
      // uncomment below and update the code to test the property leadershipPositionId
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property createMoneyAccount (base name: "create_money_account")', function() {
      // uncomment below and update the code to test the property createMoneyAccount
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

    it('should have the property sendInvite (base name: "send_invite")', function() {
      // uncomment below and update the code to test the property sendInvite
      //var instance = new ApiTitle.PostV1YouthsYouth();
      //expect(instance).to.be();
    });

  });

}));
