/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.PostV1PhotoAlbumsId();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostV1PhotoAlbumsId', function() {
    it('should create an instance of PostV1PhotoAlbumsId', function() {
      // uncomment below and update the code to test PostV1PhotoAlbumsId
      //var instance = new ApiTitle.PostV1PhotoAlbumsId();
      //expect(instance).to.be.a(ApiTitle.PostV1PhotoAlbumsId);
    });

    it('should have the property photoFileExtension (base name: "photo_file_extension")', function() {
      // uncomment below and update the code to test the property photoFileExtension
      //var instance = new ApiTitle.PostV1PhotoAlbumsId();
      //expect(instance).to.be();
    });

    it('should have the property photoFileContent (base name: "photo_file_content")', function() {
      // uncomment below and update the code to test the property photoFileContent
      //var instance = new ApiTitle.PostV1PhotoAlbumsId();
      //expect(instance).to.be();
    });

    it('should have the property albumName (base name: "album_name")', function() {
      // uncomment below and update the code to test the property albumName
      //var instance = new ApiTitle.PostV1PhotoAlbumsId();
      //expect(instance).to.be();
    });

  });

}));
