/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.PutV1EventsIdRsvp();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PutV1EventsIdRsvp', function() {
    it('should create an instance of PutV1EventsIdRsvp', function() {
      // uncomment below and update the code to test PutV1EventsIdRsvp
      //var instance = new ApiTitle.PutV1EventsIdRsvp();
      //expect(instance).to.be.a(ApiTitle.PutV1EventsIdRsvp);
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new ApiTitle.PutV1EventsIdRsvp();
      //expect(instance).to.be();
    });

    it('should have the property statusCd (base name: "status_cd")', function() {
      // uncomment below and update the code to test the property statusCd
      //var instance = new ApiTitle.PutV1EventsIdRsvp();
      //expect(instance).to.be();
    });

    it('should have the property numberOfYouthGuests (base name: "number_of_youth_guests")', function() {
      // uncomment below and update the code to test the property numberOfYouthGuests
      //var instance = new ApiTitle.PutV1EventsIdRsvp();
      //expect(instance).to.be();
    });

    it('should have the property numberOfAdultGuests (base name: "number_of_adult_guests")', function() {
      // uncomment below and update the code to test the property numberOfAdultGuests
      //var instance = new ApiTitle.PutV1EventsIdRsvp();
      //expect(instance).to.be();
    });

  });

}));
