/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.UserPrivilegesEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserPrivilegesEntity', function() {
    it('should create an instance of UserPrivilegesEntity', function() {
      // uncomment below and update the code to test UserPrivilegesEntity
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be.a(ApiTitle.UserPrivilegesEntity);
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

    it('should have the property troop (base name: "troop")', function() {
      // uncomment below and update the code to test the property troop
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

    it('should have the property troopId (base name: "troop_id")', function() {
      // uncomment below and update the code to test the property troopId
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

    it('should have the property cacheScope (base name: "cache_scope")', function() {
      // uncomment below and update the code to test the property cacheScope
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

    it('should have the property troopNumber (base name: "troop_number")', function() {
      // uncomment below and update the code to test the property troopNumber
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

    it('should have the property troopType (base name: "troop_type")', function() {
      // uncomment below and update the code to test the property troopType
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

    it('should have the property troopTypeId (base name: "troop_type_id")', function() {
      // uncomment below and update the code to test the property troopTypeId
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

    it('should have the property privileges (base name: "privileges")', function() {
      // uncomment below and update the code to test the property privileges
      //var instance = new ApiTitle.UserPrivilegesEntity();
      //expect(instance).to.be();
    });

  });

}));
