/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AchievementEntity from './model/AchievementEntity';
import AwardTypeEntity from './model/AwardTypeEntity';
import EventDetailsEntity from './model/EventDetailsEntity';
import EventEntity from './model/EventEntity';
import EventTypeEntity from './model/EventTypeEntity';
import MailingListEntity from './model/MailingListEntity';
import PhotoAlbumEntity from './model/PhotoAlbumEntity';
import PostV1Events from './model/PostV1Events';
import PostV1EventsEvent from './model/PostV1EventsEvent';
import PostV1EventsEventIdAttendance from './model/PostV1EventsEventIdAttendance';
import PostV1EventsEventIdAttendanceEventTrackersInner from './model/PostV1EventsEventIdAttendanceEventTrackersInner';
import PostV1EventsEventIdMultipleRsvp from './model/PostV1EventsEventIdMultipleRsvp';
import PostV1EventsEventIdMultipleRsvpEventTrackersInner from './model/PostV1EventsEventIdMultipleRsvpEventTrackersInner';
import PostV1MailingListsId from './model/PostV1MailingListsId';
import PostV1MailingListsIdMessage from './model/PostV1MailingListsIdMessage';
import PostV1PhotoAlbumsId from './model/PostV1PhotoAlbumsId';
import PostV1UserAchievementsId from './model/PostV1UserAchievementsId';
import PostV1UserAchievementsIdAchievement from './model/PostV1UserAchievementsIdAchievement';
import PostV1UserAchievementsIdAchievementChildrenInner from './model/PostV1UserAchievementsIdAchievementChildrenInner';
import PostV1UsersId from './model/PostV1UsersId';
import PostV1UsersIdUser from './model/PostV1UsersIdUser';
import PostV1Youths from './model/PostV1Youths';
import PostV1YouthsYouth from './model/PostV1YouthsYouth';
import PutV1EventsIdRsvp from './model/PutV1EventsIdRsvp';
import TroopPhotoEntity from './model/TroopPhotoEntity';
import UserPrivilegesEntity from './model/UserPrivilegesEntity';
import AchievementsApi from './api/AchievementsApi';
import AwardTypesApi from './api/AwardTypesApi';
import EventsApi from './api/EventsApi';
import MailingListsApi from './api/MailingListsApi';
import OfflineApi from './api/OfflineApi';
import PhotoAlbumsApi from './api/PhotoAlbumsApi';
import TokensApi from './api/TokensApi';
import UserAchievementsApi from './api/UserAchievementsApi';
import UsersApi from './api/UsersApi';
import YouthsApi from './api/YouthsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiTitle = require('index'); // See note below*.
* var xxxSvc = new ApiTitle.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiTitle.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiTitle.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiTitle.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AchievementEntity model constructor.
     * @property {module:model/AchievementEntity}
     */
    AchievementEntity,

    /**
     * The AwardTypeEntity model constructor.
     * @property {module:model/AwardTypeEntity}
     */
    AwardTypeEntity,

    /**
     * The EventDetailsEntity model constructor.
     * @property {module:model/EventDetailsEntity}
     */
    EventDetailsEntity,

    /**
     * The EventEntity model constructor.
     * @property {module:model/EventEntity}
     */
    EventEntity,

    /**
     * The EventTypeEntity model constructor.
     * @property {module:model/EventTypeEntity}
     */
    EventTypeEntity,

    /**
     * The MailingListEntity model constructor.
     * @property {module:model/MailingListEntity}
     */
    MailingListEntity,

    /**
     * The PhotoAlbumEntity model constructor.
     * @property {module:model/PhotoAlbumEntity}
     */
    PhotoAlbumEntity,

    /**
     * The PostV1Events model constructor.
     * @property {module:model/PostV1Events}
     */
    PostV1Events,

    /**
     * The PostV1EventsEvent model constructor.
     * @property {module:model/PostV1EventsEvent}
     */
    PostV1EventsEvent,

    /**
     * The PostV1EventsEventIdAttendance model constructor.
     * @property {module:model/PostV1EventsEventIdAttendance}
     */
    PostV1EventsEventIdAttendance,

    /**
     * The PostV1EventsEventIdAttendanceEventTrackersInner model constructor.
     * @property {module:model/PostV1EventsEventIdAttendanceEventTrackersInner}
     */
    PostV1EventsEventIdAttendanceEventTrackersInner,

    /**
     * The PostV1EventsEventIdMultipleRsvp model constructor.
     * @property {module:model/PostV1EventsEventIdMultipleRsvp}
     */
    PostV1EventsEventIdMultipleRsvp,

    /**
     * The PostV1EventsEventIdMultipleRsvpEventTrackersInner model constructor.
     * @property {module:model/PostV1EventsEventIdMultipleRsvpEventTrackersInner}
     */
    PostV1EventsEventIdMultipleRsvpEventTrackersInner,

    /**
     * The PostV1MailingListsId model constructor.
     * @property {module:model/PostV1MailingListsId}
     */
    PostV1MailingListsId,

    /**
     * The PostV1MailingListsIdMessage model constructor.
     * @property {module:model/PostV1MailingListsIdMessage}
     */
    PostV1MailingListsIdMessage,

    /**
     * The PostV1PhotoAlbumsId model constructor.
     * @property {module:model/PostV1PhotoAlbumsId}
     */
    PostV1PhotoAlbumsId,

    /**
     * The PostV1UserAchievementsId model constructor.
     * @property {module:model/PostV1UserAchievementsId}
     */
    PostV1UserAchievementsId,

    /**
     * The PostV1UserAchievementsIdAchievement model constructor.
     * @property {module:model/PostV1UserAchievementsIdAchievement}
     */
    PostV1UserAchievementsIdAchievement,

    /**
     * The PostV1UserAchievementsIdAchievementChildrenInner model constructor.
     * @property {module:model/PostV1UserAchievementsIdAchievementChildrenInner}
     */
    PostV1UserAchievementsIdAchievementChildrenInner,

    /**
     * The PostV1UsersId model constructor.
     * @property {module:model/PostV1UsersId}
     */
    PostV1UsersId,

    /**
     * The PostV1UsersIdUser model constructor.
     * @property {module:model/PostV1UsersIdUser}
     */
    PostV1UsersIdUser,

    /**
     * The PostV1Youths model constructor.
     * @property {module:model/PostV1Youths}
     */
    PostV1Youths,

    /**
     * The PostV1YouthsYouth model constructor.
     * @property {module:model/PostV1YouthsYouth}
     */
    PostV1YouthsYouth,

    /**
     * The PutV1EventsIdRsvp model constructor.
     * @property {module:model/PutV1EventsIdRsvp}
     */
    PutV1EventsIdRsvp,

    /**
     * The TroopPhotoEntity model constructor.
     * @property {module:model/TroopPhotoEntity}
     */
    TroopPhotoEntity,

    /**
     * The UserPrivilegesEntity model constructor.
     * @property {module:model/UserPrivilegesEntity}
     */
    UserPrivilegesEntity,

    /**
    * The AchievementsApi service constructor.
    * @property {module:api/AchievementsApi}
    */
    AchievementsApi,

    /**
    * The AwardTypesApi service constructor.
    * @property {module:api/AwardTypesApi}
    */
    AwardTypesApi,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
    * The MailingListsApi service constructor.
    * @property {module:api/MailingListsApi}
    */
    MailingListsApi,

    /**
    * The OfflineApi service constructor.
    * @property {module:api/OfflineApi}
    */
    OfflineApi,

    /**
    * The PhotoAlbumsApi service constructor.
    * @property {module:api/PhotoAlbumsApi}
    */
    PhotoAlbumsApi,

    /**
    * The TokensApi service constructor.
    * @property {module:api/TokensApi}
    */
    TokensApi,

    /**
    * The UserAchievementsApi service constructor.
    * @property {module:api/UserAchievementsApi}
    */
    UserAchievementsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The YouthsApi service constructor.
    * @property {module:api/YouthsApi}
    */
    YouthsApi
};
