/**
 * API title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.EventsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventsApi', function() {
    describe('getV1Events', function() {
      it('should call getV1Events successfully', function(done) {
        //uncomment below and update the code to test getV1Events
        //instance.getV1Events(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1EventsId', function() {
      it('should call getV1EventsId successfully', function(done) {
        //uncomment below and update the code to test getV1EventsId
        //instance.getV1EventsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1EventsTypes', function() {
      it('should call getV1EventsTypes successfully', function(done) {
        //uncomment below and update the code to test getV1EventsTypes
        //instance.getV1EventsTypes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1Events', function() {
      it('should call postV1Events successfully', function(done) {
        //uncomment below and update the code to test postV1Events
        //instance.postV1Events(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1EventsEventIdAttendance', function() {
      it('should call postV1EventsEventIdAttendance successfully', function(done) {
        //uncomment below and update the code to test postV1EventsEventIdAttendance
        //instance.postV1EventsEventIdAttendance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1EventsEventIdMultipleRsvp', function() {
      it('should call postV1EventsEventIdMultipleRsvp successfully', function(done) {
        //uncomment below and update the code to test postV1EventsEventIdMultipleRsvp
        //instance.postV1EventsEventIdMultipleRsvp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1EventsIdRsvp', function() {
      it('should call putV1EventsIdRsvp successfully', function(done) {
        //uncomment below and update the code to test putV1EventsIdRsvp
        //instance.putV1EventsIdRsvp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
